### ISSUE TITLE
Fix export

### ISSUE THREAD

**Issue by samdark** [yiisoft/var-dumper#43]
Currently export works for common cases but edge cases aren't handled well i.e. it's not suitable to export configs. We need to decide if we want to implement it properly or hide its public API.

**Comment by xepozz** [comment]
Why it doesn't suit to export configs?

**Comment by samdark** [comment]
I'll add test cases.

**Comment by samdark** [comment]
Added a test case. See https://github.com/yiisoft/var-dumper/pull/44

**Comment by xepozz** [comment]
I think it is a wrong way – trying to modify closure body.

**Comment by samdark** [comment]
What's the right way? The alternative is to add "use" statements.

**Comment by xepozz** [comment]
Better modify closure's body :)
