### ISSUE TITLE
Make more clarify description in composer.json

### ISSUE THREAD

**Issue by vjik** [yiisoft/var-dumper#70]
`Yii VarDumper` is bad.

**Comment by samdark** [comment]
?

**Comment by vjik** [comment]
![image](https://user-images.githubusercontent.com/525501/194027314-900324d4-9e11-4c63-af03-d64cfe24264a.png)

**Comment by samdark** [comment]
Enhances functionality of var_dump() and var_export(). It is dealing with recursive references, may highlight syntax and export closures.
